./ Owner: Conrad Appel
.TH SEARCHENGINE(1)
.SH NAME
searchengine \- create an index of all wikibook entries and allow user search of index
.SH SYNOPSIS
.B ./searchengine
mode [options]
.SH MODES
.SS -m / --maintenance
add files to, clear, or open index
.IP "-f filename"
add file to index
.IP -c
clear index
.IP -o
open index (test function - no functionality)
.SS -i / --interactive
loads index into memory and allows user searches
.IP -i
specify a custom index file to load
.IP -a
use an AVL Tree index
.IP -t
use a hash table index [DEFAULT]
.SS -s / --stresstest [filename]
run a set of commands from filename
.IP AV
selects AVL Tree for index data structure
.IP HT
selects Hash Table for index data structure
.IP ST
starts timer
.IP EN
stops timer & displays total time
.IP RM
clears index
.IP "OP [filepath]"
opens index stored at \fIfilepath\fR
.IP CL
saves & closes index
.IP "LD [filepath]"
indexes file stored at \fIfilepath\fR
.IP "QU [...]"
runs specified query through the query processor
.IP "PN [pageid]"
shows the contents of page with specified \fIpageid\fR
.SS -h / --help
shows this man page
.SH AUTHORS
.IP "\fBConrad Appel\fR (\fIcappel@smu.edu\fR)"
Second year B.S. Computer Engineering student at Southern Methodist University.
.IP "\fBEdward Li\fR (\fIeli@smu.edu\fR)"
