# Conrad Appel
# MATH 3316
# 9/29/14

compile_all: proj2_1 proj2_2 proj2_3

proj2_1:
	g++ test_newton.cpp mat.cpp -o newton.out

proj2_2:
	g++ test_steffensen.cpp mat.cpp -o steffensen.out

proj2_3:
	g++ kepler.cpp mat.cpp -o kepler.out

clean: 
	rm -f *.o *.out *.txt *.gch
